version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - ~/.pg/pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    container_name: postgres_django

  django:
    container_name: django_movie
    build: .
    image: app_django
    restart: always
    volumes:
      - ./movies_admin/static:/opt/app/movies_admin/static/
      - ./movies_admin/media:/opt/app/movies_admin/media/
    env_file:
      - ./.env
    depends_on:
      - postgres

  nginx:
    image:  nginx:1.25.4
    container_name: nginx_movie
    restart: always
    volumes:
      - ./movies_admin/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./movies_admin/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./movies_admin/static:/app/static/
      - ./movies_admin/media:/app/media/
    depends_on:
      - django
    ports:
      - "80:80"

volumes:
  static:
  media:



